name = "corkbookv3"
main = "index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "corkbookv3_db"
database_id = "f577c5f0-ecbd-4060-b87f-dbb720147b58"
migrations_dir = "schema"

[[r2_buckets]]
binding = "STATEMENTS"
bucket_name = "corkbookv3-statements"

[vars]
ENVIRONMENT = "development"
